package Shapes.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptCanvas = createDescriptorForCanvas();
  /*package*/ final ConceptDescriptor myConceptCircle = createDescriptorForCircle();
  /*package*/ final ConceptDescriptor myConceptColor = createDescriptorForColor();
  /*package*/ final ConceptDescriptor myConceptColorReference = createDescriptorForColorReference();
  /*package*/ final ConceptDescriptor myConceptShape = createDescriptorForShape();
  /*package*/ final ConceptDescriptor myConceptSquare = createDescriptorForSquare();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
    deps.extendedLanguage(0x4caf0310491e41f5L, 0x8a9b2006b3a94898L, "jetbrains.mps.execution.util");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptCanvas, myConceptCircle, myConceptColor, myConceptColorReference, myConceptShape, myConceptSquare);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Canvas:
        return myConceptCanvas;
      case LanguageConceptSwitch.Circle:
        return myConceptCircle;
      case LanguageConceptSwitch.Color:
        return myConceptColor;
      case LanguageConceptSwitch.ColorReference:
        return myConceptColorReference;
      case LanguageConceptSwitch.Shape:
        return myConceptShape;
      case LanguageConceptSwitch.Square:
        return myConceptSquare;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForCanvas() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Shapes", "Canvas", 0x34dddaff06a54a88L, 0x957364ae7932a56fL, 0x5d7251deed503101L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.parent(0x4caf0310491e41f5L, 0x8a9b2006b3a94898L, 0x40c1a7cb987d20d5L);
    b.origin("r:175835cc-8f7e-43b5-b678-5437b9b04f99(Shapes.structure)/6733534410778358017");
    b.version(3);
    b.aggregate("shapes", 0x5d7251deed503103L).target(0x34dddaff06a54a88L, 0x957364ae7932a56fL, 0x5d7251deed5030f1L).optional(true).ordered(true).multiple(true).origin("6733534410778358019").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForCircle() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Shapes", "Circle", 0x34dddaff06a54a88L, 0x957364ae7932a56fL, 0x5d7251deed5030f2L);
    b.class_(false, false, false);
    // extends: Shapes.structure.Shape
    b.super_(0x34dddaff06a54a88L, 0x957364ae7932a56fL, 0x5d7251deed5030f1L);
    b.origin("r:175835cc-8f7e-43b5-b678-5437b9b04f99(Shapes.structure)/6733534410778358002");
    b.version(3);
    b.property("x", 0x5d7251deed5030f6L).type(PrimitiveTypeId.INTEGER).origin("6733534410778358006").done();
    b.property("y", 0x5d7251deed5030f7L).type(PrimitiveTypeId.INTEGER).origin("6733534410778358007").done();
    b.property("radius", 0x5d7251deed5030f8L).type(PrimitiveTypeId.INTEGER).origin("6733534410778358008").done();
    b.alias("circle");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForColor() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Shapes", "Color", 0x34dddaff06a54a88L, 0x957364ae7932a56fL, 0x5d7251deed512715L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:175835cc-8f7e-43b5-b678-5437b9b04f99(Shapes.structure)/6733534410778421013");
    b.version(3);
    b.alias("color");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForColorReference() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Shapes", "ColorReference", 0x34dddaff06a54a88L, 0x957364ae7932a56fL, 0x5d7251deed526e6fL);
    b.class_(false, false, false);
    b.origin("r:175835cc-8f7e-43b5-b678-5437b9b04f99(Shapes.structure)/6733534410778504815");
    b.version(3);
    b.associate("target", 0x5d7251deed526e70L).target(0x34dddaff06a54a88L, 0x957364ae7932a56fL, 0x5d7251deed512715L).optional(false).origin("6733534410778504816").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForShape() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Shapes", "Shape", 0x34dddaff06a54a88L, 0x957364ae7932a56fL, 0x5d7251deed5030f1L);
    b.class_(false, true, false);
    b.origin("r:175835cc-8f7e-43b5-b678-5437b9b04f99(Shapes.structure)/6733534410778358001");
    b.version(3);
    b.aggregate("color", 0x5d7251deed526e89L).target(0x34dddaff06a54a88L, 0x957364ae7932a56fL, 0x5d7251deed526e6fL).optional(false).ordered(true).multiple(false).origin("6733534410778504841").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSquare() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Shapes", "Square", 0x34dddaff06a54a88L, 0x957364ae7932a56fL, 0x5d7251deed5030faL);
    b.class_(false, false, false);
    // extends: Shapes.structure.Shape
    b.super_(0x34dddaff06a54a88L, 0x957364ae7932a56fL, 0x5d7251deed5030f1L);
    b.origin("r:175835cc-8f7e-43b5-b678-5437b9b04f99(Shapes.structure)/6733534410778358010");
    b.version(3);
    b.property("upperLeftX", 0x5d7251deed5030fbL).type(PrimitiveTypeId.INTEGER).origin("6733534410778358011").done();
    b.property("upperLeftY", 0x5d7251deed5030fcL).type(PrimitiveTypeId.INTEGER).origin("6733534410778358012").done();
    b.property("size", 0x5d7251deed503100L).type(PrimitiveTypeId.INTEGER).origin("6733534410778358016").done();
    b.alias("square");
    return b.create();
  }
}
